works = [
    "abstract_inverted_index",
    "alternate_host_venues",
    "authorships",
    "best_oa_location",
    "biblio",
    "cited_by_api_url",
    "cited_by_count",
    "concepts",
    "counts_by_year",
    "created_date",
    "display_name",
    "doi",
    "host_venue",
    "id",
    "ids",
    "is_paratext",
    "is_retracted",
    "locations",
    "mesh",
    "ngrams_url",
    "open_access",
    "primary_location",
    "publication_date",
    "publication_year",
    "referenced_works",
    "related_works",
    "title",
    "type",
    "updated_date",
]
authors = [
    "cited_by_count",
    "counts_by_year",
    "created_date",
    "display_name",
    "display_name_alternatives",
    "id",
    "ids",
    "last_known_institution",
    "orcid",
    "updated_date",
    "works_api_url",
    "works_count",
    "x_concepts",
]
institutions = [
    "associated_institutions",
    "cited_by_count",
    "country_code",
    "counts_by_year",
    "created_date",
    "display_name",
    "display_name_acronyms",
    "display_name_alternatives",
    "geo",
    "homepage_url",
    "id",
    "ids",
    "image_thumbnail_url",
    "image_url",
    "international",
    "ror",
    "type",
    "updated_date",
    "works_api_url",
    "works_count",
    "x_concepts",
]
sources = [
    "abbreviated_title",
    "alternate_titles",
    "apc_usd",
    "cited_by_count",
    "country_code",
    "counts_by_year",
    "created_date",
    "display_name",
    "homepage_url",
    "host_organization",
    "id",
    "ids",
    "is_in_doaj",
    "is_oa",
    "issn",
    "issn_l",
    "publisher",
    "societies",
    "type",
    "updated_date",
    "works_api_url",
    "works_count",
    "x_concepts",
]
concepts = [
    "ancestors",
    "cited_by_count",
    "counts_by_year",
    "created_date",
    "description",
    "display_name",
    "id",
    "ids",
    "image_thumbnail_url",
    "image_url",
    "international",
    "level",
    "related_concepts",
    "updated_date",
    "wikidata",
    "works_api_url",
    "works_count",
]
publishers = [
    "alternate_titles",
    "cited_by_count",
    "country_codes",
    "counts_by_year",
    "created_date",
    "display_name",
    "hierarchy_level",
    "id",
    "ids",
    "parent_publisher",
    "sources_api_url",
    "updated_date",
    "works_count",
]
